# .graphclientrc.yml
# https://github.com/graphprotocol/graph-client/blob/main/examples/composition/.graphclientrc.yml

sources:
  - name: beefy-clm-beta
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_clu2walwem1qm01w40v3yhw1f/subgraphs/beefy-clm-arbitrum-beta/latest/gn
    transforms:
      - autoTypeMerging: true
      - autoPagination: 
          validateSchema: true
          limitOfRecords: 1000
      - rename:
          mode: wrap
          renames:
            - from:
                type: Query
                field: clmPositions
              to:
                type: Query
                field: beta_clmPositions
            - from:
                type: Query
                field: clm
              to:
                type: Query
                field: beta_clm
            - from:
                type: Query
                field: clms
              to:
                type: Query
                field: beta_clms
            

  - name: beefy-clm-prod
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_clu2walwem1qm01w40v3yhw1f/subgraphs/beefy-clm-{context.chainName:arbitrum}/clm/gn
    transforms:
      - autoTypeMerging: true
      - autoPagination: 
          validateSchema: true
          limitOfRecords: 1000

documents:
  - ./src/queries/*.graphql
