name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SUBGRAPH_TAG: ${{ ((github.event_name == 'pull_request' && github.base_ref == 'main') || (github.event_name == 'push' && github.ref == 'refs/heads/main')) && 'next' || 'latest' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Subgraph tag
        run: echo "${SUBGRAPH_TAG}"

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js  ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript type check
        run: pnpm run test

      - name: Lint & format checks
        run: pnpm run build
